version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: stop_service.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: docker-run.sh
      timeout: 120
      runas: root
