version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: script-aws/stop-service.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: script-aws/docker-run.sh
      timeout: 120
      runas: root
