version: 0.0
os: linux
files:
  - source:  /opt/codedeploy-agent/deployment-root/05ec8714-163f-404d-84ae-47d7e1a5c9bd/d-NK3X6SY36/deployment-archive
    destination: /home/ec2-user
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: root
  ApplicationBefforeInstall:
    - location: scripts/load_container.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 30
      runas: ubuntu
